In [17]:
cd ../src

/tf/gal/repos/supervised-learning-case-study/interview/src


In [18]:
run main.py

In [204]:
import numpy as np

from sklearn.metrics import accuracy_score, precision_score, recall_score

from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import BinaryCrossentropy, Reduction

import os

In [190]:
os.environ['TF_CPP_MIN_LOG_LEVEL']='2' # disable Tensorflow warnings

In [191]:
df_X = pd.read_csv("../data/onehot_dataframe_notime.csv",index_col="Unnamed: 0")
df_y = pd.read_csv("../data/onehot_y.csv",index_col="Unnamed: 0")

In [192]:
df_X.columns

Index(['Gender', 'Permissions', 'No_Unscheduled_Meetings', '3hr_call',
       'alt_phone', 'Take_Resume', 'Confirmed_Location', 'Call_Letter',
       'Married', 'is_local'],
      dtype='object')

In [174]:
df_X.drop(['Gender', 'Permissions', 'No_Unscheduled_Meetings', 
           'alt_phone', 'Take_Resume', 'Confirmed_Location', 
           'Call_Letter', 'Married', 'is_local'],
         axis = 1, inplace=True)

In [193]:
X = df_X.to_numpy()
y = df_y.to_numpy()

In [194]:
print(X,"\n")
print(y,"\n")
print(X.shape,"\n")
print(y.shape,"\n")

[[1 1 1 ... 1 0 0]
 [1 1 1 ... 1 0 0]
 [1 0 0 ... 0 0 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 0 1]
 [0 0 0 ... 0 0 1]] 

[[0]
 [0]
 [0]
 ...
 [1]
 [1]
 [1]] 

(1233, 10) 

(1233, 1) 



In [380]:
nn_hl = 10 # number of neurons in the hidden layer
num_epochs = 500 # number of times to train on the entire training set
batch_size = 128 # using batch gradient descent
mlp = define_hl_mlp_model(X, nn_hl)
activ='tanh'

num_coef = X.shape[1]
model = Sequential() # sequential model is a linear stack of layers
model.add(Dense(units=nn_hl,
                input_shape=(num_coef,),
                activation=activ, 
                use_bias=True, 
                kernel_initializer='ones', 
                bias_initializer='ones', 
                kernel_regularizer=None, 
                bias_regularizer=None, 
                activity_regularizer=None, 
                kernel_constraint=None, 
                bias_constraint=None))
model.add(Dense(units=nn_hl,
                input_shape=(num_coef,),
                activation=activ, 
                use_bias=True, 
                kernel_initializer='ones', 
                bias_initializer='ones', 
                kernel_regularizer=None, 
                bias_regularizer=None, 
                activity_regularizer=None, 
                kernel_constraint=None, 
                bias_constraint=None))
model.add(Dense(units=nn_hl,
                input_shape=(num_coef,),
                activation=activ,
                use_bias=True, 
                kernel_initializer='ones', 
                bias_initializer='ones', 
                kernel_regularizer=None, 
                bias_regularizer=None, 
                activity_regularizer=None, 
                kernel_constraint=None, 
                bias_constraint=None))
model.add(Dense(units=1,
                activation=activ,
                use_bias=True, 
                kernel_initializer='glorot_uniform')) 
sgd = SGD(lr=1e2, decay=1e-7, momentum=0.9) # using stochastic gradient descent
model.compile(loss="binary_crossentropy", optimizer=sgd, metrics=["mse"] )

In [381]:
mlp.fit(X, y, batch_size=batch_size, epochs=num_epochs, verbose=1, shuffle=True)
y_pred = mlp.predict(X)

Epoch 1/500
1233/1233 [==============================] - 0s 76us/sample - loss: 0.2288 - mse: 0.2288
Epoch 2/500
1233/1233 [==============================] - 0s 15us/sample - loss: 0.2156 - mse: 0.2156
Epoch 3/500
1233/1233 [==============================] - 0s 20us/sample - loss: 0.2134 - mse: 0.2134
Epoch 4/500
1233/1233 [==============================] - 0s 20us/sample - loss: 0.2178 - mse: 0.2178
Epoch 5/500
1233/1233 [==============================] - 0s 19us/sample - loss: 0.2122 - mse: 0.2122
Epoch 6/500
1233/1233 [==============================] - 0s 20us/sample - loss: 0.2109 - mse: 0.2109
Epoch 7/500
1233/1233 [==============================] - 0s 21us/sample - loss: 0.2116 - mse: 0.2116
Epoch 8/500
1233/1233 [==============================] - 0s 14us/sample - loss: 0.2126 - mse: 0.2126
Epoch 9/500
1233/1233 [==============================] - 0s 17us/sample - loss: 0.2274 - mse: 0.2274
Epoch 10/500
1233/1233 [==============================] - 0s 22us/sample - loss: 0.2203 - m

1233/1233 [==============================] - 0s 19us/sample - loss: 0.2036 - mse: 0.2036
Epoch 82/500
1233/1233 [==============================] - 0s 18us/sample - loss: 0.2034 - mse: 0.2034
Epoch 83/500
1233/1233 [==============================] - 0s 14us/sample - loss: 0.2023 - mse: 0.2023
Epoch 84/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.2013 - mse: 0.2013
Epoch 85/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.2034 - mse: 0.2034
Epoch 86/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.2040 - mse: 0.2040
Epoch 87/500
1233/1233 [==============================] - 0s 18us/sample - loss: 0.2034 - mse: 0.2034
Epoch 88/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.2018 - mse: 0.2018
Epoch 89/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.2022 - mse: 0.2022
Epoch 90/500
1233/1233 [==============================] - 0s 18us/sample - loss: 0.2041 - mse: 

1233/1233 [==============================] - 0s 16us/sample - loss: 0.2027 - mse: 0.2027
Epoch 161/500
1233/1233 [==============================] - 0s 17us/sample - loss: 0.2062 - mse: 0.2062
Epoch 162/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.2024 - mse: 0.2024
Epoch 163/500
1233/1233 [==============================] - 0s 17us/sample - loss: 0.2002 - mse: 0.2002
Epoch 164/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.1999 - mse: 0.1999
Epoch 165/500
1233/1233 [==============================] - 0s 17us/sample - loss: 0.2009 - mse: 0.2009
Epoch 166/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.2011 - mse: 0.2011
Epoch 167/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.2006 - mse: 0.2006
Epoch 168/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.2012 - mse: 0.2012
Epoch 169/500
1233/1233 [==============================] - 0s 17us/sample - loss: 0.200

1233/1233 [==============================] - 0s 15us/sample - loss: 0.1990 - mse: 0.1990
Epoch 240/500
1233/1233 [==============================] - 0s 18us/sample - loss: 0.2017 - mse: 0.2017
Epoch 241/500
1233/1233 [==============================] - 0s 17us/sample - loss: 0.1993 - mse: 0.1993
Epoch 242/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.1990 - mse: 0.1990
Epoch 243/500
1233/1233 [==============================] - 0s 15us/sample - loss: 0.1993 - mse: 0.1993
Epoch 244/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.2006 - mse: 0.2006
Epoch 245/500
1233/1233 [==============================] - 0s 17us/sample - loss: 0.1996 - mse: 0.1996
Epoch 246/500
1233/1233 [==============================] - 0s 19us/sample - loss: 0.1988 - mse: 0.1988
Epoch 247/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.2010 - mse: 0.2010
Epoch 248/500
1233/1233 [==============================] - 0s 17us/sample - loss: 0.201

1233/1233 [==============================] - 0s 16us/sample - loss: 0.2001 - mse: 0.2001
Epoch 319/500
1233/1233 [==============================] - 0s 17us/sample - loss: 0.2004 - mse: 0.2004
Epoch 320/500
1233/1233 [==============================] - 0s 18us/sample - loss: 0.1989 - mse: 0.1989
Epoch 321/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.1999 - mse: 0.1999
Epoch 322/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.1983 - mse: 0.1983
Epoch 323/500
1233/1233 [==============================] - 0s 17us/sample - loss: 0.1981 - mse: 0.1981
Epoch 324/500
1233/1233 [==============================] - 0s 17us/sample - loss: 0.1990 - mse: 0.1990
Epoch 325/500
1233/1233 [==============================] - 0s 18us/sample - loss: 0.1992 - mse: 0.1992
Epoch 326/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.1992 - mse: 0.1992
Epoch 327/500
1233/1233 [==============================] - 0s 14us/sample - loss: 0.198

1233/1233 [==============================] - 0s 17us/sample - loss: 0.1973 - mse: 0.1973
Epoch 398/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.1973 - mse: 0.1973
Epoch 399/500
1233/1233 [==============================] - 0s 17us/sample - loss: 0.1977 - mse: 0.1977
Epoch 400/500
1233/1233 [==============================] - 0s 18us/sample - loss: 0.1978 - mse: 0.1978
Epoch 401/500
1233/1233 [==============================] - 0s 19us/sample - loss: 0.1977 - mse: 0.1977
Epoch 402/500
1233/1233 [==============================] - 0s 18us/sample - loss: 0.1976 - mse: 0.1976
Epoch 403/500
1233/1233 [==============================] - 0s 15us/sample - loss: 0.1976 - mse: 0.1976
Epoch 404/500
1233/1233 [==============================] - 0s 17us/sample - loss: 0.1980 - mse: 0.1980
Epoch 405/500
1233/1233 [==============================] - 0s 15us/sample - loss: 0.1982 - mse: 0.1982
Epoch 406/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.197

1233/1233 [==============================] - 0s 19us/sample - loss: 0.1968 - mse: 0.1968
Epoch 477/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.1983 - mse: 0.1983
Epoch 478/500
1233/1233 [==============================] - 0s 18us/sample - loss: 0.1973 - mse: 0.1973
Epoch 479/500
1233/1233 [==============================] - 0s 15us/sample - loss: 0.1968 - mse: 0.1968
Epoch 480/500
1233/1233 [==============================] - 0s 13us/sample - loss: 0.1988 - mse: 0.1988
Epoch 481/500
1233/1233 [==============================] - 0s 12us/sample - loss: 0.1968 - mse: 0.1968
Epoch 482/500
1233/1233 [==============================] - 0s 12us/sample - loss: 0.1982 - mse: 0.1982
Epoch 483/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.1969 - mse: 0.1969
Epoch 484/500
1233/1233 [==============================] - 0s 16us/sample - loss: 0.1973 - mse: 0.1973
Epoch 485/500
1233/1233 [==============================] - 0s 15us/sample - loss: 0.197

In [382]:
print("\nTraining results")
print("yp\ty")
# y_pred = np.empty(0)
for yp, yt in zip(y_pred, y):
#     np.append(y_pred,np.array(yp[0]),axis=0)
    print("{0:0.3f}\t{1}".format(yp[0], yt[0]))


Training results
yp	y
0.786	0
0.786	0
0.450	0
0.763	0
0.340	0
0.736	1
0.736	1
0.732	1
0.736	1
0.732	0
0.736	1
0.080	0
0.736	1
0.098	1
0.736	1
0.732	1
0.732	1
0.009	0
0.736	1
0.736	0
0.098	0
0.736	1
0.736	1
0.736	1
0.303	0
0.031	0
0.056	0
0.018	0
0.782	1
0.782	1
0.732	1
0.149	0
0.738	1
0.738	0
0.325	0
0.736	1
0.782	1
0.736	0
0.738	1
0.738	1
0.359	0
0.732	1
0.024	0
0.736	1
0.738	0
0.782	1
0.516	1
0.782	1
0.736	1
0.736	1
0.738	1
0.738	0
0.738	1
0.782	0
0.782	1
0.738	1
0.736	1
0.736	1
0.736	0
0.782	0
0.782	0
0.736	1
0.736	1
0.736	1
0.736	1
0.736	0
0.736	1
0.738	1
0.738	1
0.782	1
0.736	1
0.738	1
0.782	1
0.782	1
0.736	1
0.736	1
0.736	1
0.782	0
0.736	0
0.736	1
0.736	0
0.732	1
0.732	0
0.736	1
0.294	0
0.027	0
0.019	0
0.329	0
0.346	0
0.170	0
0.738	1
0.736	1
0.736	0
0.782	0
0.736	1
0.738	0
0.738	0
0.782	1
0.738	1
0.736	1
0.736	0
0.782	1
0.736	1
0.736	0
0.736	1
0.736	1
0.738	1
0.738	1
0.736	0
0.736	0
0.732	1
0.732	1
0.736	0
0.732	1
0.782	1
0.736	1
0.736	1
0.736	0
0.736	1
0.782	1
0.024	0
0.736	0
0

0.782	1
0.736	1
0.782	1
0.782	1
0.782	1
0.736	0
0.736	1
0.736	0
0.450	0
0.732	0
0.736	1
0.019	1
0.736	1
0.736	1
0.736	1
0.736	1
0.450	0
0.736	1
0.736	1
0.450	1
0.324	1
0.736	1
0.330	1
0.450	0
0.450	1
0.450	0
0.736	1
0.450	1
0.736	1
0.330	0
0.732	1
0.732	1
0.246	0
0.450	1
0.450	1
0.450	0
0.330	0
0.738	1
0.738	1
0.375	1
0.736	0
0.736	0
0.736	1
0.736	1
0.782	1
0.450	0
0.738	1
0.738	1
0.738	1
0.736	1
0.450	1
0.450	0
0.736	1
0.736	1
0.450	1
0.450	0
0.375	0
0.375	1
0.450	1
0.782	0
0.551	0
0.450	0
0.450	0
0.736	1
0.736	0
0.732	0
0.736	1
0.736	1
0.738	1
0.736	1
0.738	1
0.782	1
0.738	1
0.736	0
0.736	0
0.782	0
0.782	1
0.736	1
0.736	0
0.736	1
0.732	1
0.736	1
0.736	0
0.738	1
0.736	1
0.738	1
0.738	1
0.738	0
0.736	1
0.736	0
0.738	0
0.736	1
0.736	1
0.738	1
0.732	0
0.738	1
0.736	0
0.736	0
0.736	0
0.736	1
0.736	0
0.736	1
0.732	1
0.738	0
0.736	0
0.736	0
0.736	1
0.736	1
0.736	1
0.732	0
0.738	1
0.736	0
0.736	0
0.736	0
0.738	0
0.738	1
0.736	0
0.736	0
0.736	1
0.736	1
0.738	1
0.738	1
0.736	1
0.736	0
0.736	1


In [383]:
for yp in y_pred:
    yp[0] = int(round(yp[0]))

In [384]:
accuracy_score(y, y_pred)
# 63% with is_local only
# 67% with 3hr_call only
# 71% with all 10 features
# 72.3% peak

0.7177615571776156